name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: uv sync
      - name: Run example
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: https://openrouter.ai/api/v1
          MODEL_NAME: openai/gpt-4o-mini
        run: uv run examples/llm.py
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: https://openrouter.ai/api/v1
        run: uv run pytest
